#!/usr/bin/env bash

echo "Run pre-push hook"

failues=0

echo "Format code"
npm run format
failues=$((failues + $?))

echo "Run tests"
npm run test
failues=$((failues + $?))

npm run build -- --verify
failues=$((failues + $?))

exit $failues